require 'action_controller'
require 'action_controller/cgi_ext'
require 'action_controller/test_process'
require 'action_view/test_case'
require 'rdiscount'
require File.dirname(__FILE__) + '/../lib/markdown_template'
